### ISSUE TITLE
UI/UX Fixes for beta release 1

### ISSUE THREAD

**Issue by joyboyisfree** [thevantageproject/PolkaAnalytics#12]
- [x] Remove copy address column from validator table
- ~Truncate the reward values to be under 5 digits long (use units such as milli, pico for smaller values and kilo, mega for larger ones)~
- ~Style the table to make data easier to distinguish (add colors to catergorize validator payment - eg high, low, medium)~
- [x] Fix validator view sizing & placement, UI elements placement and popover style and placement on hover

- [x] Fix nominator view sizing & placement, UI elements placement and popover style and placement 
- [x] Add info popup on hover to validator table columns to describe what exactly the information represents
- [x] Debounce the stake amount input
- [x] Single spinner for homepage loader (don't allow user interaction till page has finished loading
- [x] Comment out the search input in help center component until a search mechanism is implemented

**Comment by prastut** [comment]
Check for inspiration for calculator + when loading takes time: https://www.websitecarbon.com/

**Comment by joyboyisfree** [comment]
- ~Debounce input on specific views~
- [x] Error handling for 404 pages (example: [dev-polka-analytics.surge.sh/#/kusama/validator](dev-polka-analytics.surge.sh/#/kusama/validator) - should tell the user that the URL must include a validator's address, similarly, if it contains an address, but it doesn't exist, accordingly let the user know that it doesn't exist, it either might not be currently active or a nominator's address... if they think this is a bug then allow them to report it)
- [x] Show names of validators without having to hover (right above the line representing connection to the relay chain)
- [x] The nominator circles in the validator specific view look translucent, make them opaque
- [x] Remove the "Infrastructure operator for proof-of-stake networks" sub-heading on validator specific views (this could be a later addition where people could add their own taglines)
- [x] Resize the canvas (and accordingly the content inside it) for both nominator and validator specific views to fit within the view port without horizontal scroll

**Comment by bhaskarSingh** [comment]
- How should users report & reach out to us in case there is mismatch b/w validators address, i.e validator's address URL is incorrect?
- Why do we need to add debounce to the specific view input, we are not making any api request for calculation here, please elaborate why do we need it, just so we are on the same page, it's for calculation of expected daily earning for the current validator in the specific view, right?

**Comment by joyboyisfree** [comment]
@bhaskarSingh 

- Ideally there would be a proper contact form, but for now, just a link to mail us the details would be enough
- Calculating daily earnings every time the input changes is a waste of computation power and also not good practice, the user only requires the amount once they stop, there's no need to compute everything along the way. Although, this wouldn't be as high a priority as the error handling and popover issues
