### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by joyboyisfree** [thevantageproject/PolkaAnalytics#13]
The Polka Analytics web app takes minutes to complete rendering making it unuasable.

GOAL: To reduce this time to a few seconds

Possible solutions:

- For specific views, instead of waiting for the entire calculation to complete, use only the required data to render the same.
- Fetch data on hover instead of fetching all nominator’s data.

**Comment by prastut** [comment]
Solved by @bhaskarSingh
