### ISSUE TITLE
Specific Views Redesign

### ISSUE THREAD

**Issue by joyboyisfree** [thevantageproject/PolkaAnalytics#14]
**GOAL:** To gain traction on Polka Analytics by creating network effects i.e. getting people to share the Polka Analytics platform with others within the Polkadot ecosystem.

**What makes a shareable UX?**

- "Me" focused: Research finds that we love to talk about ourselves; more than 50% tweets are “me” focused (source: [Psychology of Sharing](https://www.linkedin.com/pulse/psychology-sharing-why-do-people-share-social-media-prakash-sutradhar/))
- Convey useful information
- Entertaining (as opposed to boring), clever (as opposed to dumb), hip (as opposed to dull)
- Emotion: Higher arousal = More shareable (amazement, anger, excitement as opposed to happiness, sadness, contentment)
- Public opinion: Social proof, people follow the crowd (i.e. share what others are sharing)

**Task:** To incorporate as many of the above stated properties to the specific views design as possible.

**Comment by prastut** [comment]
💡To have the money earning sound + animation inside the GIF when nominators get paid.

Inspiration: https://youtu.be/KDrA-Gy1FbI
The money popup->fade away idea that I was referencing yesterday.

**Comment by prastut** [comment]
Final design: https://xd.adobe.com/view/d1aa22bc-55db-400f-5629-c1777a647b20-a79b/

**Comment by joyboyisfree** [comment]
UI/UX Fixes to be made are listed in issue #12 @bhaskarSingh
