### ISSUE TITLE
Issues for quick launch

### ISSUE THREAD

**Issue by bhaskarSingh** [thevantageproject/PolkaAnalytics#15]
- [x] Fix specific views height issue for Nominator view
- [x] React helmet for better SEO
- [x] Amplitude for better analytics according to issue #7 
- [x] Fix specific views height issue for validator view
- [x] Handle invalid address & no address edge case for validator specific view
- [x] Remove copy validator address from the dashboard table

**Comment by saumyakaran** [comment]
@bhaskarSingh
- [ ] Input field should accept decimal values or use smaller units to enter a smaller stake amount

**Comment by joyboyisfree** [comment]
- [x] Allow users to input floats on dashboard as well as specific views @bhaskarSingh 
- [x] "Diversity" text copy change for single validator being backed on nominator specific view
- [x] Add some info to let users know that the nominator circles are clickable and will take them to nominator specific view
- [x] Change text copy in nominator view from "Expected daily ROI" to "Expect Daily Earning"

**Comment by joyboyisfree** [comment]
@bhaskarSingh
- [x] Fix input being treated as invalid when user enters a float value
