### ISSUE TITLE
Performance Improvement for specific views(Nominator & Validator)

### ISSUE THREAD

**Issue by bhaskarSingh** [thevantageproject/PolkaAnalytics#17]
Improve loading speed for nominator and validator specific view, to load within 3 seconds cause, people are impatient & expect the page to load quick, could lead to an increase in bounce rate.

**Comment by prastut** [comment]
Therefore #7 is important. With data, we would be able to identify bounce rate.

**Comment by prastut** [comment]
Putting critical labels on issues that I feel are snowballing into major issues preventing a good first impression.
