### ISSUE TITLE
Recheck Calculations everywhere

### ISSUE THREAD

**Issue by prastut** [thevantageproject/PolkaAnalytics#18]
- [x] For all validators
- [x] For all nominators

![image](https://user-images.githubusercontent.com/10279686/72129286-b18d5b00-339b-11ea-9d04-7ba5d0433d6e.png)
^ This seems way to high. Need to get it confirmed.

**Comment by bhaskarSingh** [comment]
The issue was with calculation logic on the server, which has been resolved now, @saumyakaran  confirm if calculation makes sense now or not

**Comment by joyboyisfree** [comment]
@bhaskarSingh The numbers seem sensible to me now
