### ISSUE TITLE
Nominators Earnings Leaderboard

### ISSUE THREAD

**Issue by prastut** [thevantageproject/PolkaAnalytics#25]
Currently, the home page is all about validators, should we show nominators as well and then toggle them by a button

**Comment by saumyakaran** [comment]
@prastut What purpose would this solve?

**Comment by joyboyisfree** [comment]
v1 will be a table of nominators sorted by their expected daily earnings. The table shall include the following:

- [ ] Nominator name (if available, else nominator address as currently implemented in PolkAnalytics' nominator specific view)
- [ ] Nominator's expected daily earning
- [ ] On clicking the list item, the user should be directed to the specific view of the given nominator

**Comment by joyboyisfree** [comment]
Closing in favor of https://github.com/buidl-labs/YieldScan/issues/9
