### ISSUE TITLE
Where did all the names go for validators? 

### ISSUE THREAD

**Issue by prastut** [thevantageproject/PolkaAnalytics#32]

**Comment by bhaskarSingh** [comment]
as of "@polkadot/api": "^0.100.0-beta.15" is breaking api.query.nicks.nameOf(validator) method, to resolve this issue, names has been replaced with validators ids

**Comment by prastut** [comment]
@bhaskarSingh has this issue being recognized by other people in Polkadot JS community (Riot channels, Github issues)? If not we should file an issue.

**Comment by bhaskarSingh** [comment]
Don't know about, Roit channels, but as of now this issue is not posted in their Github issues, will post the issue there, also from where do I join the Roit channel ?

**Comment by bhaskarSingh** [comment]
follow this issue for more info: https://github.com/polkadot-js/api/issues/1712

**Comment by prastut** [comment]
@saumyakaran without this there the interface has gone from slightly boring to boring. Problem to be solved.

**Comment by joyboyisfree** [comment]
@prastut Solved now using the new identity module
