### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by bhaskarSingh** [thevantageproject/PolkaAnalytics#37]
Add for specific views

**Comment by bhaskarSingh** [comment]
For specific views, home page, show error dialog, and validators table data below(suggestion)

**Comment by joyboyisfree** [comment]
- [x] API error handling for homepage i.e. when the API breaks and shows "No Data" and "-Infinity"
- [x] Error handling for validator specific view
- [x] Error handling for nominator specific view

Allow users to report error
