### ISSUE TITLE
Sorting bug

### ISSUE THREAD

**Issue by prastut** [thevantageproject/PolkaAnalytics#41]
Sorting can be ascending, descending by the number of nominators i.e two states to toggle. 

There seems to be 3 states here.

**Comment by joyboyisfree** [comment]
This is also there on the daily earnings column... @bhaskarSingh You can use https://ant.design/components/table/ as reference to fix this

**Comment by joyboyisfree** [comment]
@prastut https://github.com/ant-design/ant-design/issues/19334 Not worth the effort right now
