### ISSUE TITLE
Wrong data? 

### ISSUE THREAD

**Issue by prastut** [thevantageproject/PolkaAnalytics#69]
https://twitter.com/purestakeco/status/1230518464722460672?s=20

https://polkastats.io/validator?accountId=EqyCQvYn1cHBdzFVQHQeL1nHDcxHhjWR8V48KbDyHyuyCGV

**Comment by bhaskarSingh** [comment]
Thought: shouldn't this issue be posted on polka-analytics-api repo ?

**Comment by joyboyisfree** [comment]
Closing in favor of https://github.com/buidl-labs/polka-analytics-api/issues/26
