### ISSUE TITLE
5. Build a Twitter Bot

### ISSUE THREAD

**Issue by saumyakaran** [thevantageproject/PolkaAnalytics#8]
GOAL: To build a twitter bot which posts updates when significant events take place on the Polkadot Network

- ~Daily most backed validator~
- ~New additions to the network~
- ~Milestone events (like 1,000,000 blocks finalized)~

**Comment by prastut** [comment]
Inspiration: https://twitter.com/bitstein/status/1207143175418208258?s=20

**Comment by prastut** [comment]
Push code and have enough empathy for @bhaskarSingh to take over.

**Comment by joyboyisfree** [comment]
@bhaskarSingh Now that the performance issue is resolved, as soon as the issue #14 is resolved, we can configure the bot to post screenshots of the specific views at the end of every era, then moving on to other significant events. Our best bet to gain traction IMO would be the following: 
- [x] Top 3 previous era most backed validator
- [x] 3 Highest pool reward validators in previous era exclusive of commission

**Comment by joyboyisfree** [comment]
@bhaskarSingh
- [x] Fix the pool reward to be inclusive of comission
